[project]
name = "qe"
version = "0.1.0"
description = ""
authors = [
    {name = "Victor DEGLIAME",email = "victor.degliame@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pypdf>=4.0.0",
    "python-docx>=1.1.0",
    "requests>=2.31.0",
    "textract>=1.6.5",
    "ruff (>=0.14.14,<0.15.0)",
    "psycopg[binary] (>=3.3.2,<4.0.0)",
    "alembic (>=1.18.1,<2.0.0)",
    "polars (>=1.38.1,<2.0.0)",
    "openpyxl (>=3.1.5,<4.0.0)",
]

[tool.poetry.group.dev.dependencies]
pytest = ">=8.2.2"
pytest-cov = ">=5.0.0"
pytest-xdist = ">=3.6.1"
pytest-mock = ">=3.14.0"
pytest-asyncio = ">=1.3.0"
pre-commit = ">=4.0.1"
detect-secrets = ">=1.5.0"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.coverage.run]
source = ["qe"]
parallel = true
concurrency = ["thread", "multiprocessing"]

[tool.coverage.report]
include_namespace_packages = true

[tool.pytest.ini_options]
testpaths = ["tests"]
norecursedirs = ["dist", "build", "dev", "typings"]
asyncio_default_fixture_loop_scope = "function"
addopts = [
    "-n 4",
    "--cov=qe",
    "--cov-report=lcov:lcov.info",
    "--cov-report=json:coverage.json",
    "--cov-report=",
    "--capture=no",
    "--log-cli-level=INFO",
    "--color=yes",
]

[tool.ruff.lint]
select = ["E", "F", "W", "C", "N", "B", "Q", "S"]
ignore = [
    "D100",  # missing-module-docstring
    "D101",  # missing-class-docstring
    "D103",  # missing-function-docstring
    "E501",  # line-too-long
    "F811",  # redefined-outer-name
    "G001",  # logging-fstring-interpolation
    "N802",  # invalid-name
    "N806",  # non-lowercase-variable-in-function
    "S301",  # pickle is considered harmful
    "S311",  # standard pseudo-random generators are not suitable for security/cryptographic purposes
]

[tool.ruff.lint.per-file-ignores]
"tests/**/*.py" = [
    "B018",  # B018 - Found useless expression - necessary for testing exceptions are raised.
    "D100",  # D100 - Module dostrings not required in test files.
    "D104",  # D104 - Package dostrings not required in test files.
    "S101",  # S101 - Use of assert in tests is fine.
]

[tool.mypy]
ignore_missing_imports = true
disable_error_code = ["call-overload", "import-untyped", "assignment"]
check_untyped_defs = true

[tool.bandit]
tests = ["B201", "B301"]
